import { describe, expect, it } from 'vitest'
import { APIError } from './api/client'
import { canSubmitFollow, cloneFollowSnapshot, followDefaultsPath, isFollowRevisionConflict, splitRuleText, type FollowDefaults, type FollowExecutionSnapshot } from './follows'

const snapshot: FollowExecutionSnapshot = { version: 2, routing_policy: 'source_priority', seasons: [1], site_ids: [2], media_library_id: 3, schedule: { kind: 'interval', minutes: 360 }, filters: { resolutions: [], video_codecs: [], qualities: [], include_keywords: [], exclude_keywords: [], release_groups: [], exclude_release_groups: [], min_seeders: 1, max_age_hours: null, min_size_bytes: null, max_size_bytes: null }, max_resources_per_run: 3, download_priority: 0 }
describe('follow contracts', () => {
  it('builds bounded safe defaults paths and rule arrays', () => { expect(followDefaultsPath(100)).toBe('/api/v1/follows/defaults?media_type=tv&tmdb_id=100'); expect(splitRuleText('WEB, WEB，HEVC\n')).toEqual(['WEB', 'HEVC']) })
  it('clones immutable snapshots and validates route bindings', () => { const clone = cloneFollowSnapshot(snapshot); clone.seasons.push(2); expect(snapshot.seasons).toEqual([1]); const defaults: FollowDefaults = { snapshot, sites: [{ id: 2, name: 'Mikan', site_type: 'bt' }], downloaders: [{ id: 'd', name: '115', type: 'pan115_offline', connection_id: 8 }], media_libraries: [{ id: 3, name: '115 TV', storage_type: 'pan115', connection_id: 8 }], subscribed_seasons: [], coverage: {} as never }; expect(canSubmitFollow(defaults, snapshot)).toBe(true); expect(canSubmitFollow(null, snapshot)).toBe(false) })
  it('allows mixed PT, BT and cloud sites without binding the follow to one downloader', () => { const defaults: FollowDefaults = { snapshot, sites: [{ id: 1, name: 'PT', site_type: 'pt' }, { id: 2, name: 'Mikan', site_type: 'bt' }, { id: 6, name: '115 TG', site_type: 'cloud_share' }], downloaders: [{ id: 'pan', name: '115', type: 'pan115_offline', connection_id: 8 }, { id: 'qbit', name: 'qBit', type: 'qbittorrent' }], media_libraries: [{ id: 3, name: '115 TV', storage_type: 'pan115', connection_id: 8 }, { id: 5, name: 'Local', storage_type: 'local' }], subscribed_seasons: [], coverage: {} as never }; expect(canSubmitFollow(defaults, { ...snapshot, site_ids: [1, 2, 6] })).toBe(true); expect(canSubmitFollow(defaults, { ...snapshot, site_ids: [1, 999] })).toBe(false) })
  it('recognizes revision conflicts without treating other API failures as reload signals', () => { expect(isFollowRevisionConflict(new APIError(409, 'follow_revision_conflict', 'conflict'))).toBe(true); expect(isFollowRevisionConflict(new APIError(409, 'follow_season_conflict', 'conflict'))).toBe(false) })

})
