package services

import "errors"

const (
	CodeInvalidRequest                  = "INVALID_REQUEST"
	CodeNotAuthenticated                = "NOT_AUTHENTICATED"
	CodePermissionDenied                = "PERMISSION_DENIED"
	CodeNotFound                        = "NOT_FOUND"
	CodeConflict                        = "CONFLICT"
	CodeSetupComplete                   = "SETUP_ALREADY_COMPLETE"
	CodeInvalidCredentials              = "INVALID_CREDENTIALS"
	CodeLoginRateLimited                = "LOGIN_RATE_LIMITED"
	CodeOwnerProtected                  = "OWNER_PROTECTED"
	CodeLastAdminRequired               = "LAST_ADMIN_REQUIRED"
	CodeSelfModification                = "SELF_MODIFICATION_FORBIDDEN"
	CodePrivilegeEscalation             = "PRIVILEGE_ESCALATION"
	CodeProtectedRole                   = "PROTECTED_ROLE"
	CodeRoleInUse                       = "ROLE_IN_USE"
	CodeRecoveryRequired                = "OWNER_RECOVERY_REQUIRED"
	CodeStorageTypeUnsupported          = "storage_type_unsupported"
	CodeStorageNameRequired             = "storage_name_required"
	CodeStorageNameConflict             = "storage_name_conflict"
	CodeStoragePathConflict             = "storage_path_conflict"
	CodeProfileValidation               = "media_classification_profile_validation"
	CodeProfileNameRequired             = "media_classification_profile_name_required"
	CodeProfileNameConflict             = "media_classification_profile_name_conflict"
	CodeProfileProtected                = "media_classification_profile_protected"
	CodeProfileRevisionConflict         = "media_classification_profile_revision_conflict"
	CodeProfileInUse                    = "media_classification_profile_in_use"
	CodeRuntimeLogFilterInvalid         = "runtime_log_filter_invalid"
	CodeRuntimeLogPolicyInvalid         = "runtime_log_policy_invalid"
	CodeRuntimeLogUnavailable           = "runtime_log_unavailable"
	CodeMediaLibraryNameRequired        = "media_library_name_required"
	CodeMediaLibraryNameConflict        = "media_library_name_conflict"
	CodeMediaLibraryPathInvalid         = "media_library_path_invalid"
	CodeMediaLibraryOverlap             = "media_library_overlap"
	CodeMediaLibraryStorageUnavailable  = "media_library_storage_unavailable"
	CodeMediaLibraryProfileUnavailable  = "media_library_profile_unavailable"
	CodeMediaLibraryScanFailed          = "media_library_scan_failed"
	CodeMediaLibraryBusy                = "media_library_busy"
	CodeDownloaderTypeUnsupported       = "downloader_type_unsupported"
	CodeDownloaderNameRequired          = "downloader_name_required"
	CodeDownloaderNameConflict          = "downloader_name_conflict"
	CodeDownloaderStorageRequired       = "downloader_storage_required"
	CodeDownloaderStorageUnavailable    = "downloader_storage_unavailable"
	CodeDownloaderInUse                 = "downloader_in_use"
	CodeDownloaderUnavailable           = "downloader_unavailable"
	CodeDownloadStagingRequired         = "download_staging_required"
	CodeDownloadStagingUnavailable      = "download_staging_unavailable"
	CodeDownloadSourceInvalid           = "download_source_invalid"
	CodeDownloadTorrentInvalid          = "download_torrent_invalid"
	CodeTransferMediaUnrecognized       = "transfer_media_unrecognized"
	CodeTransferEpisodeUnrecognized     = "transfer_episode_unrecognized"
	CodeTransferRouteUnsupported        = "transfer_route_unsupported"
	CodeTMDBTokenInvalid                = "tmdb_token_invalid"
	CodeTMDBUnavailable                 = "tmdb_unavailable"
	CodeConnectionProviderUnsupported   = "connection_provider_unsupported"
	CodeConnectionNameRequired          = "connection_name_required"
	CodeConnectionNameConflict          = "connection_name_conflict"
	CodeConnectionInUse                 = "connection_in_use"
	CodeConnectionUnavailable           = "connection_unavailable"
	CodePan115CookieInvalid             = "pan115_cookie_invalid"
	CodeEmbyEndpointInvalid             = "emby_endpoint_invalid"
	CodeEmbyAPIKeyInvalid               = "emby_api_key_invalid"
	CodeEmbyUnavailable                 = "emby_unavailable"
	CodeEmbyGatewayUnavailable          = "emby_gateway_unavailable"
	CodeEmbyGatewayAliasInvalid         = "emby_gateway_alias_invalid"
	CodeEmbyGatewayAliasReserved        = "emby_gateway_alias_reserved"
	CodeEmbyGatewayAliasConflict        = "emby_gateway_alias_conflict"
	CodeEmbySummaryPartial              = "emby_summary_partial"
	CodeEmbyPlaybackTicketInvalid       = "emby_playback_ticket_invalid"
	CodeProxySignatureInvalid           = "proxy_signature_invalid"
	CodeProxySignatureExpired           = "proxy_signature_expired"
	CodeProxyTargetUnavailable          = "proxy_target_unavailable"
	CodeProxyUpstreamUnavailable        = "proxy_upstream_unavailable"
	CodeProxyHeadersUnsupported         = "proxy_headers_unsupported"
	CodeProxyUnavailable                = "proxy_unavailable"
	CodeProxyDeviceLimit                = "proxy_device_limit"
	CodePluginRepositoryURLInvalid      = "plugin_repository_url_invalid"
	CodePluginRepositoryConflict        = "plugin_repository_conflict"
	CodePluginRepositoryUnavailable     = "plugin_repository_unavailable"
	CodePluginRegistryInvalid           = "plugin_registry_invalid"
	CodePluginRegistryTooLarge          = "plugin_registry_too_large"
	CodePluginRegistryRateLimited       = "plugin_registry_rate_limited"
	CodePluginRepositoryRevision        = "plugin_repository_revision_conflict"
	CodePluginAssetInvalid              = "plugin_asset_url_invalid"
	CodePluginAssetUnavailable          = "plugin_asset_download_failed"
	CodePluginManifestInvalid           = "plugin_manifest_invalid"
	CodePluginManifestMismatch          = "plugin_manifest_registry_mismatch"
	CodePluginPackageDigest             = "plugin_package_digest_mismatch"
	CodePluginPackageInvalid            = "plugin_package_invalid"
	CodePluginPackageTooLarge           = "plugin_package_too_large"
	CodePluginPackageConflict           = "plugin_package_identity_conflict"
	CodePluginSourceChange              = "plugin_source_change_requires_confirmation"
	CodePluginSignatureUntrusted        = "plugin_signature_untrusted"
	CodePluginRuntimeUnavailable        = "plugin_runtime_unavailable"
	CodePluginRuntimeStartFailed        = "plugin_runtime_start_failed"
	CodePluginRuntimeStopFailed         = "plugin_runtime_stop_failed"
	CodePluginRuntimeStateFailed        = "plugin_runtime_state_persist_failed"
	CodePluginCleanupFailed             = "plugin_package_cleanup_failed"
	CodePluginAlreadyInstalled          = "plugin_already_installed"
	CodePluginPreviewExpired            = "plugin_install_preview_expired"
	CodePluginPermissionChanged         = "plugin_permission_changed"
	CodePluginRevisionConflict          = "plugin_installation_revision_conflict"
	CodePluginRollbackUnavailable       = "plugin_rollback_unavailable"
	CodePluginOnlineLibraryUnavailable  = "plugin_online_library_unavailable"
	CodePluginOnlineAuthentication      = "plugin_online_authentication_required"
	CodePluginOnlineAccessRestricted    = "plugin_online_access_restricted"
	CodePluginOnlineQualityUnavailable  = "plugin_online_quality_unavailable"
	CodePluginOnlineRateLimited         = "plugin_online_rate_limited"
	CodePluginFeedRateLimited           = "plugin_feed_rate_limited"
	CodePluginResponseInvalid           = "plugin_response_invalid"
	CodePluginAssetExpired              = "plugin_asset_expired"
	CodeDiscoveryProviderUnavailable    = "discovery_provider_unavailable"
	CodeDiscoveryResponseInvalid        = "discovery_response_invalid"
	CodeDiscoverySectionInvalid         = "discovery_section_invalid"
	CodeSiteKindUnsupported             = "site_kind_unsupported"
	CodeSiteNameRequired                = "site_name_required"
	CodeSiteNameConflict                = "site_name_conflict"
	CodeSiteURLInvalid                  = "site_url_invalid"
	CodeSiteBTHostUnsupported           = "site_bt_host_unsupported"
	CodeSiteCredentialInvalid           = "site_credential_invalid"
	CodeSiteUnavailable                 = "site_unavailable"
	CodeSiteAuthentication              = "site_authentication_failed"
	CodeSiteRateLimited                 = "site_rate_limited"
	CodeSiteResponseInvalid             = "site_response_invalid"
	CodeSiteResultExpired               = "site_result_expired"
	CodeCookieCloudInvalid              = "cookiecloud_invalid"
	CodeCookieCloudDisabled             = "cookiecloud_disabled"
	CodeCookieCloudAuthentication       = "cookiecloud_authentication_failed"
	CodeCookieCloudUnavailable          = "cookiecloud_unavailable"
	CodeCookieCloudResponseInvalid      = "cookiecloud_response_invalid"
	CodeCredentialRevealUnavailable     = "credential_reveal_unavailable"
	CodeAIConfigurationInvalid          = "ai_configuration_invalid"
	CodeAIAuthentication                = "ai_authentication_failed"
	CodeAIUnavailable                   = "ai_provider_unavailable"
	CodeAIRateLimited                   = "ai_rate_limited"
	CodeAIResponseInvalid               = "ai_response_invalid"
	CodeReorganizationUnavailable       = "media_reorganization_unavailable"
	CodeReorganizationPreviewExpired    = "media_reorganization_preview_expired"
	CodeReorganizationBoundaryChanged   = "media_reorganization_boundary_changed"
	CodeReorganizationConflict          = "media_reorganization_conflict"
	CodeTransferDeletionScopeInvalid    = "transfer_deletion_scope_invalid"
	CodeTransferDeletionUnavailable     = "transfer_deletion_unavailable"
	CodeTransferDeletionPreviewExpired  = "transfer_deletion_preview_expired"
	CodeTransferDeletionBoundaryChanged = "transfer_deletion_boundary_changed"
	CodeTransferDeletionPartial         = "transfer_deletion_partial"
)

// AppError is a stable, client-safe domain error.
type AppError struct {
	Code    string
	Message string
	Cause   error
}

func (e *AppError) Error() string { return e.Message }
func (e *AppError) Unwrap() error { return e.Cause }

func appError(code, message string, cause error) error {
	return &AppError{Code: code, Message: message, Cause: cause}
}

// ErrorCode returns the stable code for a domain error.
func ErrorCode(err error) string {
	var target *AppError
	if errors.As(err, &target) {
		return target.Code
	}
	return "INTERNAL_ERROR"
}

// ErrorMessage returns the safe message for a domain error.
func ErrorMessage(err error) string {
	var target *AppError
	if errors.As(err, &target) {
		return target.Message
	}
	return "服务器内部错误"
}
