package httpserver

import (
	"net/http"
	"os"

	"github.com/gin-gonic/gin"
	"github.com/rs/zerolog"
	"github.com/yuanjing-hash/ohmycine/server/internal/authz"
	"github.com/yuanjing-hash/ohmycine/server/internal/config"
	"github.com/yuanjing-hash/ohmycine/server/internal/handlers"
	"github.com/yuanjing-hash/ohmycine/server/internal/middleware"
	"github.com/yuanjing-hash/ohmycine/server/internal/services"
	"github.com/yuanjing-hash/ohmycine/server/webui"
)

func New(cfg config.Config, api *handlers.API, auth *services.AuthService, log zerolog.Logger) *gin.Engine {
	if cfg.Environment == "production" {
		gin.SetMode(gin.ReleaseMode)
	}
	router := gin.New()
	_ = router.SetTrustedProxies(nil)
	router.Use(gin.Recovery(), middleware.RequestID(), middleware.SecurityHeaders(), middleware.Logger(log))
	router.Any("/proxy/strm/:opaque", api.SignedSTRMProxy)
	router.Any("/emby/:gateway", api.EmbyGateway)
	router.Any("/emby/:gateway/*path", api.EmbyGateway)
	router.GET("/api/v1/assets/library-covers/:name", api.PlayerLibraryArtwork)
	router.GET("/api/v1/assets/plugin-covers/:digest", api.PluginLibraryArtwork)
	router.GET("/api/v1/assets/generated-library-covers/:digest", api.GeneratedLibraryArtwork)
	router.GET("/cookiecloud", api.CookieCloudRoot)
	router.POST("/cookiecloud", api.CookieCloudRoot)
	router.POST("/cookiecloud/update", api.CookieCloudUpdate)
	// Native Player routes are registered before browser-only Origin/CSRF
	// middleware. They use their own strict bearer boundary instead.
	player := router.Group("/api/v1/player")
	player.Use(middleware.NoStore())
	player.POST("/auth/login", api.PlayerLogin)
	playerProtected := player.Group("")
	playerProtected.Use(middleware.DeviceAuth(auth))
	playerProtected.POST("/auth/logout", api.PlayerLogout)
	playerProtected.GET("/bootstrap", api.PlayerBootstrap)
	playerProtected.GET("/devices", api.PlayerDevices)
	playerProtected.DELETE("/devices/:id", api.RevokePlayerDevice)
	playerProtected.GET("/media-libraries", api.PlayerMediaLibraries)
	playerProtected.GET("/media-changes", api.PlayerMediaChanges)
	playerProtected.GET("/media-libraries/:id/categories", api.PlayerMediaLibraryCategories)
	playerProtected.GET("/media-libraries/:id/catalog", api.PlayerMediaLibraryCatalog)
	playerProtected.GET("/media-libraries/:id/catalog/:work", api.PlayerMediaLibraryDetail)
	playerProtected.GET("/search", api.PlayerSearch)
	playerProtected.GET("/media-entries/:id/stream", api.PlayerMediaEntryStream)
	playerProtected.HEAD("/media-entries/:id/stream", api.PlayerMediaEntryStream)
	playerProtected.GET("/online-libraries", api.PlayerOnlineLibraries)
	playerProtected.GET("/online-libraries/:id/navigation", api.PlayerOnlineNavigation)
	playerProtected.GET("/online-libraries/:id/navigation/:nodeToken/children", api.PlayerOnlineNavigationChildren)
	playerProtected.GET("/online-libraries/:id/feeds/:routeKey", api.PlayerOnlineFeed)
	playerProtected.POST("/online-libraries/:id/feeds/:routeKey/refresh", api.PlayerOnlineFeedRefresh)
	playerProtected.GET("/home-contributions", api.PlayerHomeContributions)
	playerProtected.GET("/online-libraries/:id/search", api.PlayerOnlineSearch)
	playerProtected.GET("/online-libraries/:id/items/:itemId", api.PlayerOnlineDetail)
	playerProtected.POST("/online-libraries/:id/items/:itemId/playback", api.PlayerOnlinePlayback)
	playerProtected.POST("/online-libraries/:id/items/:itemId/actions/:action", api.PlayerOnlineAction)
	playerProtected.POST("/online-libraries/:id/items/:itemId/download", api.PlayerOnlineDownload)
	playerProtected.POST("/online-libraries/:id/items/:itemId/progress", api.PlayerOnlineProgress)
	playerProtected.GET("/online-history", api.PlayerOnlineHistory)
	playerProtected.GET("/online-assets/:opaque", api.PlayerOnlineAsset)
	playerProtected.HEAD("/online-assets/:opaque", api.PlayerOnlineAsset)

	router.Use(middleware.BrowserMutationProtection(cfg.AllowedOrigins()))
	v1 := router.Group("/api/v1")
	v1.GET("/health", api.Health)
	v1.GET("/setup/status", api.SetupStatus)
	v1.POST("/setup/owner", api.SetupOwner)
	v1.POST("/auth/login", api.Login)

	protected := v1.Group("")
	protected.Use(middleware.Auth(auth, api.CookieName()), middleware.CSRF(auth))
	protected.POST("/auth/logout", api.Logout)
	protected.GET("/auth/me", api.Me)
	protected.GET("/auth/csrf", api.CSRF)
	protected.GET("/player-devices", middleware.NoStore(), middleware.RequirePermission(authz.PermissionConnectionsRead), api.PlayerDevices)
	protected.DELETE("/player-devices/:id", middleware.NoStore(), middleware.RequirePermission(authz.PermissionConnectionsUpdate), api.RevokePlayerDevice)
	protected.GET("/dashboard", middleware.RequirePermission(authz.PermissionDashboardRead), api.Dashboard)
	protected.GET("/discovery/recommendations", middleware.NoStore(), middleware.RequirePermission(authz.PermissionDiscoveryRead), api.DiscoveryRecommendations)
	protected.POST("/discovery/recommendations/refresh", middleware.NoStore(), middleware.RequirePermission(authz.PermissionDiscoveryRead), api.RefreshDiscoveryRecommendations)
	protected.GET("/discovery/details/:provider/:mediaType/:providerID", middleware.NoStore(), middleware.RequirePermission(authz.PermissionDiscoveryRead), api.DiscoveryDetail)
	protected.GET("/discovery/images/:provider/:token", middleware.RequirePermission(authz.PermissionDiscoveryRead), api.DiscoveryImage)
	protected.GET("/permissions", middleware.RequirePermission(authz.PermissionRolesRead), api.Permissions)
	protected.GET("/users", middleware.RequirePermission(authz.PermissionUsersRead), api.Users)
	protected.POST("/users", middleware.RequirePermission(authz.PermissionUsersCreate), api.CreateUser)
	protected.PATCH("/users/:id", middleware.RequirePermission(authz.PermissionUsersUpdate), api.UpdateUser)
	protected.POST("/users/:id/disable", middleware.RequirePermission(authz.PermissionUsersDisable), func(c *gin.Context) { api.SetUserEnabled(c, false) })
	protected.POST("/users/:id/enable", middleware.RequirePermission(authz.PermissionUsersUpdate), func(c *gin.Context) { api.SetUserEnabled(c, true) })
	protected.POST("/users/:id/reset-password", middleware.RequirePermission(authz.PermissionUsersUpdate), api.ResetPassword)
	protected.PUT("/users/:id/roles", middleware.RequirePermission(authz.PermissionRolesAssign), api.AssignRoles)
	protected.DELETE("/users/:id", middleware.RequirePermission(authz.PermissionUsersDelete), api.DeleteUser)
	protected.GET("/roles", middleware.RequirePermission(authz.PermissionRolesRead), api.Roles)
	protected.POST("/roles", middleware.RequirePermission(authz.PermissionRolesCreate), api.CreateRole)
	protected.PATCH("/roles/:id", middleware.RequirePermission(authz.PermissionRolesUpdate), api.UpdateRole)
	protected.PUT("/roles/:id/permissions", middleware.RequirePermission(authz.PermissionRolesUpdate), api.SetRolePermissions)
	protected.DELETE("/roles/:id", middleware.RequirePermission(authz.PermissionRolesDelete), api.DeleteRole)
	protected.GET("/audit", middleware.RequirePermission(authz.PermissionAuditRead), api.Audit)
	protected.GET("/storages", middleware.RequirePermission(authz.PermissionStoragesRead), api.Storages)
	protected.GET("/filesystem/roots", middleware.NoStore(), middleware.RequirePermission(authz.PermissionStoragesBrowse), api.DirectoryRoots)
	protected.GET("/filesystem/directories", middleware.NoStore(), middleware.RequirePermission(authz.PermissionStoragesBrowse), api.Directories)
	protected.GET("/storages/:id/directory", middleware.NoStore(), middleware.RequirePermission(authz.PermissionStoragesBrowse), api.StorageDirectory)
	protected.POST("/storages", middleware.RequirePermission(authz.PermissionStoragesCreate), api.CreateStorage)
	protected.PATCH("/storages/:id", middleware.RequirePermission(authz.PermissionStoragesUpdate), api.UpdateStorage)
	protected.DELETE("/storages/:id", middleware.RequirePermission(authz.PermissionStoragesDelete), api.DeleteStorage)
	protected.POST("/storages/:id/test", middleware.RequirePermission(authz.PermissionStoragesTest), api.TestStorage)
	protected.GET("/media-classification-profiles", middleware.RequirePermission(authz.PermissionMediaClassificationProfilesRead), api.MediaClassificationProfiles)
	protected.GET("/media-classification-profiles/:id", middleware.RequirePermission(authz.PermissionMediaClassificationProfilesRead), api.MediaClassificationProfile)
	protected.POST("/media-classification-profiles", middleware.RequirePermission(authz.PermissionMediaClassificationProfilesCreate), api.CreateMediaClassificationProfile)
	protected.POST("/media-classification-profiles/:id/copy", middleware.RequirePermission(authz.PermissionMediaClassificationProfilesCreate), api.CopyMediaClassificationProfile)
	protected.PATCH("/media-classification-profiles/:id", middleware.RequirePermission(authz.PermissionMediaClassificationProfilesUpdate), api.UpdateMediaClassificationProfile)
	protected.DELETE("/media-classification-profiles/:id", middleware.RequirePermission(authz.PermissionMediaClassificationProfilesDelete), api.DeleteMediaClassificationProfile)
	protected.GET("/media-libraries", middleware.RequirePermission(authz.PermissionMediaLibrariesRead), api.MediaLibraries)
	protected.PUT("/media-libraries/order", middleware.RequirePermission(authz.PermissionMediaLibrariesUpdate), api.ReorderMediaLibraries)
	protected.GET("/media-libraries/:id", middleware.RequirePermission(authz.PermissionMediaLibrariesRead), api.MediaLibrary)
	protected.POST("/media-libraries", middleware.RequirePermission(authz.PermissionMediaLibrariesCreate), api.CreateMediaLibrary)
	protected.PUT("/media-libraries/:id", middleware.RequirePermission(authz.PermissionMediaLibrariesUpdate), api.UpdateMediaLibrary)
	protected.DELETE("/media-libraries/:id", middleware.RequirePermission(authz.PermissionMediaLibrariesDelete), api.DeleteMediaLibrary)
	protected.POST("/media-libraries/:id/scan", middleware.RequirePermission(authz.PermissionMediaLibrariesScan), api.ScanMediaLibrary)
	protected.POST("/media-libraries/:id/retry", middleware.RequirePermission(authz.PermissionMediaLibrariesScan), api.RetryMediaLibrary)
	protected.GET("/media-libraries/:id/entries", middleware.RequirePermission(authz.PermissionMediaLibrariesRead), api.MediaLibraryEntries)
	protected.GET("/media-libraries/:id/recognitions", middleware.NoStore(), middleware.RequirePermission(authz.PermissionMediaLibrariesRead), api.MediaLibraryRecognitions)
	protected.POST("/media-libraries/:id/recognitions/:token/retry", middleware.NoStore(), middleware.RequirePermission(authz.PermissionMediaLibrariesScan), api.RetryMediaLibraryRecognition)
	protected.GET("/media-libraries/:id/recognitions/:token/tmdb-candidates", middleware.NoStore(), middleware.RequirePermission(authz.PermissionMediaLibrariesRead), api.MediaLibraryRecognitionCandidates)
	protected.PUT("/media-libraries/:id/recognitions/:token/override", middleware.NoStore(), middleware.RequirePermission(authz.PermissionMediaLibrariesScan), api.OverrideMediaLibraryRecognition)
	protected.DELETE("/media-libraries/:id/recognitions/:token/override", middleware.NoStore(), middleware.RequirePermission(authz.PermissionMediaLibrariesScan), api.ClearMediaLibraryRecognitionOverride)
	protected.GET("/media-libraries/:id/catalog", middleware.RequirePermission(authz.PermissionMediaLibrariesRead), api.MediaLibraryCatalog)
	protected.GET("/media-libraries/:id/catalog/:work", middleware.RequirePermission(authz.PermissionMediaLibrariesRead), api.MediaLibraryCatalogDetail)
	protected.GET("/media-libraries/:id/runs", middleware.RequirePermission(authz.PermissionMediaLibrariesRead), api.MediaLibraryRuns)
	protected.GET("/strm/libraries", middleware.NoStore(), middleware.RequirePermission(authz.PermissionSTRMRunsRead), api.STRMLibraries)
	protected.GET("/strm/runs", middleware.NoStore(), middleware.RequirePermission(authz.PermissionSTRMRunsRead), api.STRMRuns)
	protected.GET("/strm/artifacts", middleware.NoStore(), middleware.RequirePermission(authz.PermissionSTRMRunsRead), api.STRMArtifacts)
	protected.POST("/strm/libraries/:id/reconcile", middleware.RequirePermission(authz.PermissionSTRMRunsCreate), api.ReconcileSTRM)
	protected.POST("/strm/runs/:run/retry", middleware.RequirePermission(authz.PermissionSTRMRunsCreate), api.RetrySTRMRun)
	protected.POST("/strm/libraries/:id/cleanup/preview", middleware.NoStore(), middleware.RequirePermission(authz.PermissionSTRMCleanup), api.PreviewSTRMCleanup)
	protected.POST("/strm/libraries/:id/cleanup/execute", middleware.NoStore(), middleware.RequirePermission(authz.PermissionSTRMCleanup), api.ExecuteSTRMCleanup)
	jobRead := middleware.RequireAnyPermission(authz.PermissionJobsReadOwn, authz.PermissionJobsReadAll)
	jobControl := middleware.RequireAnyPermission(authz.PermissionJobsControlOwn, authz.PermissionJobsControlAll)
	protected.GET("/jobs", middleware.NoStore(), jobRead, api.Jobs)
	protected.GET("/jobs/:id", middleware.NoStore(), jobRead, api.Job)
	protected.GET("/jobs/:id/attempts", middleware.NoStore(), jobRead, api.JobAttempts)
	protected.GET("/jobs/:id/timeline", middleware.NoStore(), jobRead, api.JobTimeline)
	protected.POST("/jobs/:id/pause", jobRead, jobControl, api.JobControl("pause"))
	protected.POST("/jobs/:id/resume", jobRead, jobControl, api.JobControl("resume"))
	protected.POST("/jobs/:id/cancel", jobRead, jobControl, api.JobControl("cancel"))
	protected.POST("/jobs/:id/retry", jobRead, jobControl, api.JobControl("retry"))
	protected.POST("/jobs/:id/actions/:version/respond", middleware.RequirePermission(authz.PermissionJobsRespond), api.RespondJobAction)
	protected.PUT("/job-lanes/:jobType/:priority/order", jobRead, middleware.RequirePermission(authz.PermissionJobsReorder), api.ReorderJobLane)
	protected.GET("/queue/policies", middleware.NoStore(), jobRead, api.QueuePolicies)
	protected.PUT("/queue/policies/:jobType", middleware.RequirePermission(authz.PermissionQueuePoliciesManage), api.UpdateQueuePolicy)
	transferRead := middleware.RequireAnyPermission(authz.PermissionTransfersReadOwn, authz.PermissionTransfersReadAll)
	jobEventRead := middleware.RequireAnyPermission(authz.PermissionJobsReadOwn, authz.PermissionJobsReadAll, authz.PermissionTransfersReadOwn, authz.PermissionTransfersReadAll)
	protected.GET("/jobs/events/ws", jobEventRead, api.QueueEvents)
	protected.GET("/transfers", middleware.NoStore(), transferRead, api.Transfers)
	protected.GET("/transfers/:id", middleware.NoStore(), transferRead, api.Transfer)
	protected.DELETE("/transfers/:id", middleware.NoStore(), transferRead, jobControl, api.DeleteTransfer)

	connectionAPI := v1.Group("")
	connectionAPI.Use(middleware.NoStore(), middleware.Auth(auth, api.CookieName()), middleware.CSRF(auth))
	connectionAPI.GET("/connections", middleware.RequirePermission(authz.PermissionConnectionsRead), api.Connections)
	connectionAPI.POST("/credentials/reveal", middleware.RequirePermission(authz.PermissionConnectionsSecretsExport), api.RevealCredential)
	connectionAPI.GET("/connections/:id/directories", middleware.RequirePermission(authz.PermissionConnectionsRead), middleware.RequirePermission(authz.PermissionStoragesBrowse), api.ConnectionDirectories)
	connectionAPI.POST("/connections", middleware.RequirePermission(authz.PermissionConnectionsCreate), api.CreateConnection)
	connectionAPI.PATCH("/connections/:id", middleware.RequirePermission(authz.PermissionConnectionsUpdate), api.UpdateConnection)
	connectionAPI.POST("/connections/:id/test", middleware.RequirePermission(authz.PermissionConnectionsTest), api.TestConnection)
	connectionAPI.GET("/connections/:id/emby-summary", middleware.RequirePermission(authz.PermissionConnectionsRead), api.EmbyManagementSummary)
	connectionAPI.GET("/connections/:id/emby-gateway", middleware.RequirePermission(authz.PermissionConnectionsRead), api.EmbyGatewaySettings)
	connectionAPI.PATCH("/connections/:id/emby-gateway", middleware.RequirePermission(authz.PermissionConnectionsUpdate), api.UpdateEmbyGatewaySettings)
	connectionAPI.DELETE("/connections/:id", middleware.RequirePermission(authz.PermissionConnectionsDelete), api.DeleteConnection)
	connectionAPI.GET("/connections/:id/media-server-libraries", middleware.RequirePermission(authz.PermissionConnectionsRead), api.MediaServerUpstreamLibraries)
	connectionAPI.GET("/media-server-refresh-targets", middleware.RequirePermission(authz.PermissionConnectionsRead), middleware.RequirePermission(authz.PermissionMediaLibrariesRead), api.MediaServerRefreshTargets)
	connectionAPI.POST("/media-server-refresh-targets", middleware.RequirePermission(authz.PermissionConnectionsUpdate), middleware.RequirePermission(authz.PermissionMediaLibrariesUpdate), api.CreateMediaServerRefreshTarget)
	connectionAPI.PATCH("/media-server-refresh-targets/:id", middleware.RequirePermission(authz.PermissionConnectionsUpdate), middleware.RequirePermission(authz.PermissionMediaLibrariesUpdate), api.UpdateMediaServerRefreshTarget)
	connectionAPI.DELETE("/media-server-refresh-targets/:id", middleware.RequirePermission(authz.PermissionConnectionsUpdate), middleware.RequirePermission(authz.PermissionMediaLibrariesUpdate), api.DeleteMediaServerRefreshTarget)
	connectionAPI.POST("/media-server-refresh-targets/:id/test", middleware.RequirePermission(authz.PermissionConnectionsTest), middleware.RequirePermission(authz.PermissionMediaLibrariesRead), api.TestMediaServerRefreshTarget)
	connectionAPI.POST("/media-server-refresh-targets/:id/refresh", middleware.RequirePermission(authz.PermissionMediaServersRefresh), api.RefreshMediaServerTarget)
	connectionAPI.POST("/media-server-refresh-targets/:id/retry", middleware.RequirePermission(authz.PermissionMediaServersRefresh), api.RetryMediaServerRefreshTarget)

	ptAPI := v1.Group("")
	ptAPI.Use(middleware.NoStore(), middleware.Auth(auth, api.CookieName()), middleware.CSRF(auth))
	ptAPI.GET("/discovery/pt-search", middleware.RequirePermission(authz.PermissionDiscoveryRead), api.PTSearch)
	ptAPI.GET("/discovery/pt-search/stream", middleware.RequirePermission(authz.PermissionDiscoveryRead), api.PTSearchStream)
	ptAPI.GET("/discovery/torrent-search", middleware.RequirePermission(authz.PermissionDiscoveryRead), api.TorrentSearch)
	ptAPI.GET("/discovery/torrent-search/stream", middleware.RequirePermission(authz.PermissionDiscoveryRead), api.TorrentSearchStream)
	ptAPI.POST("/discovery/pt-results/recognize", middleware.RequirePermission(authz.PermissionDiscoveryRead), api.RecognizePTResult)
	ptAPI.POST("/discovery/torrent-results/recognize", middleware.RequirePermission(authz.PermissionDiscoveryRead), api.RecognizeTorrentResult)
	ptAPI.POST("/discovery/pt-results/tmdb-candidates", middleware.RequirePermission(authz.PermissionDiscoveryRead), api.PTResultRecognitionCandidates)
	ptAPI.POST("/discovery/torrent-results/tmdb-candidates", middleware.RequirePermission(authz.PermissionDiscoveryRead), api.PTResultRecognitionCandidates)
	ptAPI.PUT("/discovery/pt-results/recognition-override", middleware.RequirePermission(authz.PermissionDiscoveryRead), middleware.RequirePermission(authz.PermissionDownloadsCreate), api.OverridePTResultRecognition)
	ptAPI.PUT("/discovery/torrent-results/recognition-override", middleware.RequirePermission(authz.PermissionDiscoveryRead), middleware.RequirePermission(authz.PermissionDownloadsCreate), api.OverridePTResultRecognition)
	ptAPI.POST("/discovery/downloads", middleware.RequirePermission(authz.PermissionDownloadsCreate), api.CreateDiscoveryDownload)
	ptAPI.GET("/sites", middleware.RequirePermission(authz.PermissionSystemAdmin), api.Sites)
	ptAPI.GET("/sites/catalog", middleware.RequirePermission(authz.PermissionSystemAdmin), api.SiteCatalog)
	ptAPI.POST("/sites", middleware.RequirePermission(authz.PermissionSystemAdmin), api.CreateSite)
	ptAPI.PATCH("/sites/:id", middleware.RequirePermission(authz.PermissionSystemAdmin), api.UpdateSite)
	ptAPI.DELETE("/sites/:id", middleware.RequirePermission(authz.PermissionSystemAdmin), api.DeleteSite)
	ptAPI.POST("/sites/:id/test", middleware.RequirePermission(authz.PermissionSystemAdmin), api.TestSite)
	ptAPI.GET("/settings/sites/cookiecloud", middleware.RequirePermission(authz.PermissionSystemAdmin), api.CookieCloudSettings)
	ptAPI.PATCH("/settings/sites/cookiecloud", middleware.RequirePermission(authz.PermissionSystemAdmin), api.UpdateCookieCloudSettings)
	ptAPI.POST("/settings/sites/cookiecloud/sync", middleware.RequirePermission(authz.PermissionSystemAdmin), api.SyncCookieCloud)

	downloadAPI := v1.Group("")
	downloadAPI.Use(middleware.NoStore(), middleware.Auth(auth, api.CookieName()), middleware.CSRF(auth))
	downloadAPI.GET("/downloaders", middleware.RequirePermission(authz.PermissionDownloadersRead), api.Downloaders)
	downloadAPI.POST("/downloaders", middleware.RequirePermission(authz.PermissionDownloadersCreate), api.CreateDownloader)
	downloadAPI.PATCH("/downloaders/:id", middleware.RequirePermission(authz.PermissionDownloadersUpdate), api.UpdateDownloader)
	downloadAPI.DELETE("/downloaders/:id", middleware.RequirePermission(authz.PermissionDownloadersDelete), api.DeleteDownloader)
	downloadAPI.POST("/downloaders/:id/test", middleware.RequirePermission(authz.PermissionDownloadersTest), api.TestDownloader)
	downloadAPI.GET("/downloads", middleware.RequireAnyPermission(authz.PermissionDownloadsReadOwn, authz.PermissionDownloadsReadAll), api.Downloads)
	downloadAPI.POST("/downloads", middleware.RequirePermission(authz.PermissionDownloadsCreate), api.CreateDownload)
	downloadAPI.GET("/downloads/:id/tmdb-candidates", middleware.RequireAnyPermission(authz.PermissionDownloadsReadOwn, authz.PermissionDownloadsReadAll), api.DownloadRecognitionCandidates)
	downloadAPI.PUT("/downloads/:id/recognition-override", middleware.RequireAnyPermission(authz.PermissionJobsControlOwn, authz.PermissionJobsControlAll), api.OverrideDownloadRecognition)
	downloadAPI.PUT("/downloads/:id/import-target", middleware.RequireAnyPermission(authz.PermissionJobsControlOwn, authz.PermissionJobsControlAll), api.RetargetDownloadImport)
	downloadAPI.DELETE("/downloads/:id", middleware.RequireAnyPermission(authz.PermissionJobsControlOwn, authz.PermissionDownloadsManageAll), api.DeleteDownload)
	downloadAPI.GET("/seeding-tasks", middleware.RequireAnyPermission(authz.PermissionDownloadsReadOwn, authz.PermissionDownloadsReadAll), api.SeedingTasks)
	downloadAPI.POST("/seeding-tasks/:id/stop", middleware.RequireAnyPermission(authz.PermissionJobsControlOwn, authz.PermissionDownloadsManageAll), api.StopSeedingTask)

	downloadSettingsAPI := v1.Group("/settings/downloads")
	downloadSettingsAPI.Use(middleware.NoStore(), middleware.Auth(auth, api.CookieName()), middleware.CSRF(auth))
	downloadSettingsAPI.GET("", middleware.RequirePermission(authz.PermissionSettingsRead), api.DownloadSettings)
	downloadSettingsAPI.GET("/directory", middleware.RequirePermission(authz.PermissionSettingsRead), middleware.RequirePermission(authz.PermissionStoragesBrowse), api.DownloadSettingsDirectory)
	downloadSettingsAPI.PATCH("", middleware.RequirePermission(authz.PermissionSettingsUpdate), api.UpdateDownloadSettings)
	seedingSettingsAPI := v1.Group("/settings/seeding")
	seedingSettingsAPI.Use(middleware.NoStore(), middleware.Auth(auth, api.CookieName()), middleware.CSRF(auth))
	seedingSettingsAPI.GET("", middleware.RequirePermission(authz.PermissionSettingsRead), api.SeedingSettings)
	seedingSettingsAPI.PATCH("", middleware.RequirePermission(authz.PermissionSettingsUpdate), api.UpdateSeedingSettings)
	metadataSettingsAPI := v1.Group("/settings/metadata")
	metadataSettingsAPI.Use(middleware.NoStore(), middleware.Auth(auth, api.CookieName()), middleware.CSRF(auth))
	metadataSettingsAPI.GET("", middleware.RequirePermission(authz.PermissionSettingsRead), api.MetadataSettings)
	metadataSettingsAPI.PATCH("", middleware.RequirePermission(authz.PermissionSettingsUpdate), api.UpdateMetadataSettings)
	metadataSettingsAPI.POST("/test", middleware.RequirePermission(authz.PermissionSettingsUpdate), api.TestMetadataSettings)
	metadataSettingsAPI.POST("/test-token", middleware.RequirePermission(authz.PermissionSettingsUpdate), api.TestAndSetMetadataToken)
	metadataSettingsAPI.POST("/test-api", middleware.RequirePermission(authz.PermissionSettingsUpdate), api.TestAndSetMetadataRoute("api"))
	metadataSettingsAPI.POST("/test-image", middleware.RequirePermission(authz.PermissionSettingsUpdate), api.TestAndSetMetadataRoute("image"))

	runtimeLogs := v1.Group("/runtime-logs")
	runtimeLogs.Use(middleware.NoStore(), middleware.Auth(auth, api.CookieName()), middleware.CSRF(auth))
	runtimeLogs.GET("", middleware.RequirePermission(authz.PermissionLogsRead), api.RuntimeLogs)
	runtimeLogs.GET("/facets", middleware.RequirePermission(authz.PermissionLogsRead), api.RuntimeLogFacets)
	runtimeLogs.GET("/settings", middleware.RequirePermission(authz.PermissionLogsRead), api.RuntimeLogSettings)
	runtimeLogs.PATCH("/settings", middleware.RequirePermission(authz.PermissionLogsConfigure), api.UpdateRuntimeLogSettings)
	runtimeLogs.POST("/export", middleware.RequirePermission(authz.PermissionLogsExport), api.ExportRuntimeLogs)

	pluginAPI := v1.Group("")
	pluginAPI.Use(middleware.NoStore(), middleware.Auth(auth, api.CookieName()), middleware.CSRF(auth))
	pluginAPI.GET("/plugin-repositories", middleware.RequirePermission(authz.PermissionPluginsRead), api.PluginRepositories)
	pluginAPI.POST("/plugin-repositories", middleware.RequirePermission(authz.PermissionPluginsInstall), api.CreatePluginRepository)
	pluginAPI.PATCH("/plugin-repositories/:id", middleware.RequirePermission(authz.PermissionPluginsInstall), api.UpdatePluginRepository)
	pluginAPI.DELETE("/plugin-repositories/:id", middleware.RequirePermission(authz.PermissionPluginsInstall), api.DeletePluginRepository)
	pluginAPI.PUT("/plugin-repositories/order", middleware.RequirePermission(authz.PermissionPluginsInstall), api.ReorderPluginRepositories)
	pluginAPI.POST("/plugin-repositories/:id/refresh", middleware.RequirePermission(authz.PermissionPluginsInstall), api.RefreshPluginRepository)
	pluginAPI.GET("/plugins/marketplace", middleware.RequirePermission(authz.PermissionPluginsRead), api.PluginMarketplace)
	pluginAPI.GET("/plugins/installed", middleware.RequirePermission(authz.PermissionPluginsRead), api.InstalledPlugins)
	pluginAPI.POST("/plugins/:plugin_id/installation-preview", middleware.RequirePermission(authz.PermissionPluginsInstall), api.PreviewPluginInstallation)
	pluginAPI.POST("/plugins/:plugin_id/install", middleware.RequirePermission(authz.PermissionPluginsInstall), api.ConfirmPluginInstall)
	pluginAPI.POST("/plugins/:plugin_id/update", middleware.RequirePermission(authz.PermissionPluginsInstall), api.ConfirmPluginUpdate)
	pluginAPI.POST("/plugins/:plugin_id/enable", middleware.RequirePermission(authz.PermissionPluginsInstall), api.EnablePlugin)
	pluginAPI.POST("/plugins/:plugin_id/disable", middleware.RequirePermission(authz.PermissionPluginsInstall), api.DisablePlugin)
	pluginAPI.POST("/plugins/:plugin_id/rollback", middleware.RequirePermission(authz.PermissionPluginsInstall), api.RollbackPlugin)
	pluginAPI.DELETE("/plugins/:plugin_id", middleware.RequirePermission(authz.PermissionPluginsInstall), api.UninstallPlugin)
	pluginAPI.GET("/plugins/:plugin_id/connections", middleware.RequirePermission(authz.PermissionPluginsRead), api.PluginConnections)
	pluginAPI.POST("/plugins/:plugin_id/connections", middleware.RequirePermission(authz.PermissionPluginsInstall), api.CreatePluginConnection)
	pluginAPI.PATCH("/plugins/:plugin_id/connections/:connection_id", middleware.RequirePermission(authz.PermissionPluginsInstall), api.UpdatePluginConnection)
	pluginAPI.DELETE("/plugins/:plugin_id/connections/:connection_id", middleware.RequirePermission(authz.PermissionPluginsInstall), api.DeletePluginConnection)
	pluginAPI.POST("/plugins/:plugin_id/connections/:connection_id/auth/start", middleware.RequirePermission(authz.PermissionPluginsInstall), api.StartPluginConnectionAuth)
	pluginAPI.POST("/plugins/:plugin_id/connections/:connection_id/auth/poll", middleware.RequirePermission(authz.PermissionPluginsInstall), api.PollPluginConnectionAuth)

	if assets, ok := webui.Assets(); ok {
		webui.Register(router, assets)
	} else {
		router.NoRoute(func(c *gin.Context) {
			c.JSON(http.StatusNotFound, gin.H{"code": 40401, "message": "not found", "data": nil})
		})
	}
	return router
}

func NewLogger(environment string) zerolog.Logger {
	zerolog.TimeFieldFormat = zerolog.TimeFormatUnixMs
	writer := zerolog.ConsoleWriter{Out: os.Stdout}
	if environment == "production" {
		return zerolog.New(os.Stdout).With().Timestamp().Logger()
	}
	return zerolog.New(writer).With().Timestamp().Logger()
}
