<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { api, APIError } from '@/api/client'
import { Permissions } from '@/auth/generated-permissions'
import { useAuthStore } from '@/stores/auth'
import { filtersFromQuery, filtersToParams, filtersToQuery, type RuntimeLogFilters } from '@/runtime-logs'
import type { RuntimeLogEntry, RuntimeLogFacets, RuntimeLogResult, RuntimeLogSettings } from '@/types/api'

const auth=useAuthStore();const route=useRoute();const router=useRouter()
const filters=reactive<RuntimeLogFilters>(filtersFromQuery(route.query));const entries=ref<RuntimeLogEntry[]>([]);const facets=ref<RuntimeLogFacets>({levels:[],modules:[],components:[],operations:[],plugin_ids:[]});const settings=ref<RuntimeLogSettings|null>(null)
const loading=ref(false);const saving=ref(false);const exporting=ref(false);const error=ref('');const cursor=ref('');const partial=ref(false);const malformed=ref(0);let loadSerial=0
const advanced=ref(Object.entries(filters).some(([key,value])=>key.endsWith('Id')&&value));const canExport=computed(()=>auth.can(Permissions.LogsExport));const canConfigure=computed(()=>auth.can(Permissions.LogsConfigure))

function localInput(iso:string){const date=new Date(iso);const pad=(n:number)=>String(n).padStart(2,'0');return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`}
function updateDate(field:'from'|'to',value:string){const date=new Date(value);if(!Number.isNaN(date.getTime()))filters[field]=date.toISOString()}
function levelClass(level:string){return `runtime-level runtime-level--${level}`}
function stringify(value:unknown){try{return JSON.stringify(value,null,2)}catch{return String(value)}}
const operationLabels:Record<string,string>={server_lifecycle:'服务生命周期',http_request:'HTTP请求',system_health:'系统健康',authentication:'认证与初始化',dashboard:'仪表盘',access_control:'用户与权限',audit_log:'审计日志',storage_management:'存储管理',directory_browsing:'目录浏览',media_rule_management:'分类规则管理',media_library_management:'媒体库管理',connection_management:'连接管理',downloader_management:'下载器管理',system_settings:'系统设置',metadata_configuration:'元数据设置',runtime_logging:'运行日志',connection_probe:'连接检测',provider_life_event:'115生活事件',library_initial_scan:'媒体库首次扫描',library_incremental_scan:'媒体库增量扫描',library_full_scan:'媒体库全量扫描',library_event_scan:'媒体库事件增量',media_recognition:'媒体识别',metadata_snapshot:'元数据快照',media_artifact:'媒体产物',strm_generation:'STRM生成',incremental_strm_generation:'增量STRM生成',full_strm_generation:'全量STRM生成',signed_proxy:'302代理',emby_proxy_gateway:'Emby302网关',pan115_sidecar_upload:'115旁挂上传',artifact_cleanup:'产物清理',download_task:'下载任务',download_classification:'下载预分类',pan115_offline_download:'115离线下载',pan115_share_ingest:'115分享摄取',pan115_cloud_transfer:'115云端整理',media_transfer:'媒体整理',seeding_management:'做种管理',task_queue:'系统任务队列'}
function operationLabel(code:string){return operationLabels[code]??code}

async function load(append=false){const serial=++loadSerial;loading.value=true;error.value='';try{const params=filtersToParams(filters);params.set('limit','100');if(append&&cursor.value)params.set('cursor',cursor.value);const result=await api<RuntimeLogResult>(`/api/v1/runtime-logs?${params}`);if(serial!==loadSerial)return;entries.value=append?[...entries.value,...result.list]:result.list;cursor.value=result.next_cursor??'';partial.value=result.partial;malformed.value=result.malformed;if(!append)await router.replace({query:filtersToQuery(filters)})}catch(reason){if(serial===loadSerial)error.value=reason instanceof Error?reason.message:'运行日志加载失败'}finally{if(serial===loadSerial)loading.value=false}}
async function loadMetadata(){const params=filtersToParams(filters);try{facets.value=await api<RuntimeLogFacets>(`/api/v1/runtime-logs/facets?${params}`)}catch{/* list remains usable */}try{settings.value=await api<RuntimeLogSettings>('/api/v1/runtime-logs/settings')}catch{/* read permission may still query */}}
async function apply(){cursor.value='';await Promise.all([load(false),loadMetadata()])}
function reset(){Object.assign(filters,filtersFromQuery({}));void apply()}
async function saveSettings(){if(!settings.value)return;saving.value=true;error.value='';try{settings.value=await api<RuntimeLogSettings>('/api/v1/runtime-logs/settings',{method:'PATCH',body:JSON.stringify(settings.value)})}catch(reason){error.value=reason instanceof Error?reason.message:'设置保存失败'}finally{saving.value=false}}
async function exportLogs(){exporting.value=true;error.value='';try{const headers=new Headers({'Content-Type':'application/json'});const csrf=await api<{csrf_token:string}>('/api/v1/auth/csrf');headers.set('X-CSRF-Token',csrf.csrf_token);const body=Object.fromEntries(filtersToParams(filters).entries());const response=await fetch('/api/v1/runtime-logs/export',{method:'POST',credentials:'include',headers,body:JSON.stringify({from:body.from,to:body.to,levels:body.level?[body.level]:[],modules:body.module?[body.module]:[],components:body.component?[body.component]:[],operations:body.operation?[body.operation]:[],plugin_ids:body.plugin_id?[body.plugin_id]:[],keyword:body.keyword??'',request_id:body.request_id??'',task_id:body.task_id??'',library_id:body.library_id??'',connection_id:body.connection_id??'',storage_id:body.storage_id??'',downloader_id:body.downloader_id??'',scan_run_id:body.scan_run_id??''})});if(!response.ok)throw new APIError(response.status,'EXPORT_FAILED','导出失败');const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='ohmycine-runtime-logs.jsonl.gz';link.click();URL.revokeObjectURL(url)}catch(reason){error.value=reason instanceof Error?reason.message:'导出失败'}finally{exporting.value=false}}
onMounted(()=>void Promise.all([load(),loadMetadata()]))
</script>

<template>
  <section>
    <div class="flex flex-wrap items-start justify-between gap-4"><div><h1 class="m-0 text-3xl font-800">运行日志</h1><p class="page-description mt-2">日志已经在写入前脱敏，可按模块、插件和业务关联定位问题。</p></div><div class="flex gap-2"><button v-if="canExport" class="btn-secondary" :disabled="exporting" @click="exportLogs">{{ exporting?'正在导出…':'导出筛选结果' }}</button><button class="btn-secondary" :disabled="loading" @click="apply">刷新</button></div></div>
    <p v-if="error" class="semantic-error mt-5 p-3" role="alert">{{ error }}</p>
    <p v-if="settings?.health.degraded" class="semantic-warning mt-5 p-3">文件日志当前处于降级状态（{{ settings.health.reason }}），stdout 仍继续输出。</p>
    <form class="panel runtime-filter mt-6" @submit.prevent="apply">
      <label><span class="label">开始时间</span><input class="input" type="datetime-local" :value="localInput(filters.from)" @change="updateDate('from',($event.target as HTMLInputElement).value)"></label>
      <label><span class="label">结束时间</span><input class="input" type="datetime-local" :value="localInput(filters.to)" @change="updateDate('to',($event.target as HTMLInputElement).value)"></label>
      <label><span class="label">级别</span><select v-model="filters.level" class="input"><option value="">全部</option><option v-for="item in ['debug','info','warn','error']" :key="item">{{ item }}</option></select></label>
      <label><span class="label">模块</span><select v-model="filters.module" class="input"><option value="">全部</option><option v-for="item in facets.modules" :key="item">{{ item }}</option></select></label>
      <label><span class="label">组件</span><select v-model="filters.component" class="input"><option value="">全部</option><option v-for="item in facets.components" :key="item">{{ item }}</option></select></label>
      <label><span class="label">业务操作</span><select v-model="filters.operation" class="input"><option value="">全部</option><option v-for="item in facets.operations" :key="item" :value="item">{{ operationLabel(item) }}</option></select></label>
      <label><span class="label">插件</span><select v-model="filters.pluginId" class="input"><option value="">全部</option><option v-for="item in facets.plugin_ids" :key="item" :value="item">{{ item }}</option></select></label>
      <label class="runtime-filter__keyword"><span class="label">关键字</span><input v-model="filters.keyword" class="input" maxlength="128" placeholder="仅搜索脱敏后的消息"></label>
      <div class="runtime-filter__actions"><button class="btn-primary" :disabled="loading">查询</button><button type="button" class="btn-secondary" @click="reset">重置</button><button type="button" class="btn-secondary" @click="advanced=!advanced">{{ advanced?'收起':'高级筛选' }}</button></div>
      <div v-if="advanced" class="runtime-filter__advanced"><label v-for="field in [{k:'requestId',n:'Request ID'},{k:'taskId',n:'任务 ID'},{k:'libraryId',n:'媒体库 ID'},{k:'connectionId',n:'连接 ID'},{k:'storageId',n:'存储 ID'},{k:'downloaderId',n:'下载器 ID'},{k:'scanRunId',n:'扫描 Run ID'}]" :key="field.k"><span class="label">{{ field.n }}</span><input v-model="filters[field.k as keyof RuntimeLogFilters]" class="input"></label></div>
    </form>
    <div v-if="partial||malformed" class="semantic-warning mt-4 p-3">查询受到扫描上限或文件读取影响，结果可能不完整；跳过 {{ malformed }} 条损坏记录。</div>
    <div v-if="loading&&entries.length===0" class="text-subtle mt-8">正在读取运行日志…</div>
    <div v-else-if="entries.length===0" class="panel text-subtle mt-6">当前筛选范围内没有日志。</div>
    <div v-else class="runtime-list mt-5">
      <details v-for="(entry,index) in entries" :key="`${entry.timestamp}-${index}`" class="panel runtime-entry"><summary><time>{{ new Date(entry.timestamp).toLocaleString() }}</time><span :class="levelClass(entry.level)">{{ entry.level }}</span><strong>{{ entry.operation_label ? `【${entry.operation_label}】` : `${entry.module}/${entry.component}` }}</strong><span v-if="entry.plugin_id" class="status-chip">{{ entry.plugin_id }}</span><span class="runtime-entry__message">{{ entry.message }}</span></summary><dl><dt>module / component</dt><dd><pre>{{ entry.module }} / {{ entry.component }}</pre></dd><template v-for="(value,key) in entry.fields" :key="key"><dt>{{ key }}</dt><dd><pre>{{ stringify(value) }}</pre></dd></template></dl></details>
    </div>
    <button v-if="cursor" class="btn-secondary mt-4 w-full" :disabled="loading" @click="load(true)">加载更多</button>
    <form v-if="settings&&canConfigure" class="panel mt-8" @submit.prevent="saveSettings"><h2 class="m-0 text-lg">轮转与保留设置</h2><p class="text-subtle mt-2 text-sm">目录由部署环境控制，不在页面暴露；修改会写入审计日志。</p><div class="runtime-settings mt-5"><label><span class="label">最低级别</span><select v-model="settings.level" class="input"><option v-for="item in ['debug','info','warn','error']" :key="item">{{ item }}</option></select></label><label><span class="label">单文件 MiB</span><input v-model.number="settings.max_file_mib" class="input" type="number" min="1" max="256"></label><label><span class="label">压缩分片数</span><input v-model.number="settings.max_backups" class="input" type="number" min="1" max="100"></label><label><span class="label">保留天数</span><input v-model.number="settings.retention_days" class="input" type="number" min="1" max="365"></label><label><span class="label">总上限 MiB</span><input v-model.number="settings.max_total_mib" class="input" type="number" min="32" max="10240"></label></div><button class="btn-primary mt-5" :disabled="saving">{{ saving?'正在保存…':'保存日志策略' }}</button></form>
  </section>
</template>

<style scoped>
.runtime-filter{display:grid;grid-template-columns:repeat(6,minmax(8rem,1fr));gap:1rem}.runtime-filter__keyword{grid-column:span 4}.runtime-filter__actions{display:flex;grid-column:span 2;align-items:end;gap:.5rem}.runtime-filter__advanced{display:grid;grid-column:1/-1;grid-template-columns:repeat(auto-fit,minmax(12rem,1fr));gap:1rem;border-top:1px solid var(--border);padding-top:1rem}.runtime-list{display:grid;gap:.55rem}.runtime-entry{padding:.8rem 1rem}.runtime-entry summary{display:grid;grid-template-columns:11rem 4rem minmax(8rem,12rem) auto minmax(12rem,1fr);align-items:center;gap:.75rem;cursor:pointer}.runtime-entry time{color:var(--text-subtle);font-size:.75rem}.runtime-entry__message{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.runtime-entry dl{display:grid;grid-template-columns:minmax(8rem,12rem) 1fr;margin:1rem 0 0;border-top:1px solid var(--border);padding-top:.75rem}.runtime-entry dt{color:var(--text-subtle);font-size:.75rem}.runtime-entry dd{margin:0}.runtime-entry pre{overflow:auto;margin:0;color:var(--text-muted);white-space:pre-wrap;overflow-wrap:anywhere;font-size:.72rem}.runtime-level{font-size:.68rem;font-weight:800;text-transform:uppercase}.runtime-level--error{color:var(--danger)}.runtime-level--warn{color:var(--warning)}.runtime-level--info{color:var(--accent)}.runtime-level--debug{color:var(--text-subtle)}.runtime-settings{display:grid;grid-template-columns:repeat(auto-fit,minmax(10rem,1fr));gap:1rem}@media(max-width:1100px){.runtime-filter{grid-template-columns:repeat(3,1fr)}.runtime-filter__keyword{grid-column:span 2}.runtime-filter__actions{grid-column:span 1}.runtime-entry summary{grid-template-columns:9rem 3.5rem minmax(8rem,1fr);}.runtime-entry__message{grid-column:1/-1}.runtime-entry summary>.status-chip{display:none}}@media(max-width:650px){.runtime-filter{grid-template-columns:1fr}.runtime-filter__keyword,.runtime-filter__actions{grid-column:1}.runtime-filter__actions{flex-wrap:wrap}.runtime-entry summary{grid-template-columns:1fr auto}.runtime-entry strong,.runtime-entry__message{grid-column:1/-1}.runtime-entry dl{grid-template-columns:1fr}.runtime-entry dt{margin-top:.5rem}}
</style>
