<script setup lang="ts">
import { computed, nextTick, onMounted, ref } from 'vue'
import { createFollow, loadFollow, loadFollowDefaults, splitRuleText, updateFollow, cloneFollowSnapshot, canSubmitFollow, compatibleFollowDownloaders, compatibleFollowSites, isFollowRevisionConflict, type FollowDefaults, type FollowExecutionSnapshot, type FollowSummary } from '@/follows'

const props = defineProps<{ tmdbId: number; title: string; year?: number; posterRef?: string; initialSeasons?: number[]; follow?: FollowSummary }>()
const emit = defineEmits<{ close: []; saved: [FollowSummary] }>()
const defaults = ref<FollowDefaults | null>(null)
const snapshot = ref<FollowExecutionSnapshot | null>(null)
const loading = ref(true); const saving = ref(false); const error = ref('')
const dialog = ref<HTMLElement | null>(null)
const revision = ref(props.follow?.revision ?? 0)
const includeText = ref(''); const excludeText = ref(''); const releaseText = ref(''); const excludeReleaseText = ref('')
const resolutionOptions = ['2160p', '1080p', '720p']; const codecOptions = ['HEVC', 'AV1', 'H.264/AVC']; const qualityOptions = ['WEB-DL', 'BluRay', 'REMUX']
const ready = computed(() => canSubmitFollow(defaults.value, snapshot.value))
const routeDownloaders = computed(() => defaults.value && snapshot.value ? compatibleFollowDownloaders(defaults.value, snapshot.value.media_library_id) : [])
const routeSites = computed(() => defaults.value && snapshot.value ? compatibleFollowSites(defaults.value, snapshot.value.media_library_id, snapshot.value.downloader_id) : [])

function applySnapshot(value: FollowExecutionSnapshot) { snapshot.value = cloneFollowSnapshot(value); includeText.value = snapshot.value.filters.include_keywords.join(', '); excludeText.value = snapshot.value.filters.exclude_keywords.join(', '); releaseText.value = snapshot.value.filters.release_groups.join(', '); excludeReleaseText.value = snapshot.value.filters.exclude_release_groups.join(', ') }
onMounted(async () => { try { defaults.value = await loadFollowDefaults(props.tmdbId); applySnapshot(props.follow?.snapshot ?? defaults.value.snapshot); if (!props.follow && props.initialSeasons?.length && snapshot.value) snapshot.value.seasons = [...props.initialSeasons]; await nextTick(); dialog.value?.focus() } catch (reason) { error.value = reason instanceof Error ? reason.message : '订阅配置加载失败' } finally { loading.value = false } })
function toggleNumber(values: number[], value: number) { const index = values.indexOf(value); if (index >= 0) values.splice(index, 1); else values.push(value); values.sort((a, b) => a - b) }
function toggleOrderedNumber(values: number[], value: number) { const index = values.indexOf(value); if (index >= 0) values.splice(index, 1); else values.push(value) }
function syncLibraryRoute() { if (!snapshot.value) return; if (!routeDownloaders.value.some(item => item.id === snapshot.value?.downloader_id)) snapshot.value.downloader_id = ''; snapshot.value.site_ids = [] }
function syncDownloaderRoute() { if (!snapshot.value) return; const allowed = new Set(routeSites.value.map(item => item.id)); snapshot.value.site_ids = snapshot.value.site_ids.filter(id => allowed.has(id)) }
function toggleString(values: string[], value: string) { const index = values.indexOf(value); if (index >= 0) values.splice(index, 1); else values.push(value) }
function seasonUnavailable(value: number) { return defaults.value?.subscribed_seasons.includes(value) && !props.follow?.snapshot.seasons.includes(value) }
async function save() { if (!snapshot.value || !ready.value) return; saving.value = true; error.value = ''; snapshot.value.filters.include_keywords = splitRuleText(includeText.value); snapshot.value.filters.exclude_keywords = splitRuleText(excludeText.value); snapshot.value.filters.release_groups = splitRuleText(releaseText.value); snapshot.value.filters.exclude_release_groups = splitRuleText(excludeReleaseText.value); try { const saved = props.follow ? await updateFollow(props.follow.id, revision.value, snapshot.value) : await createFollow({ tmdb_id: props.tmdbId, title: props.title, year: props.year, poster_ref: props.posterRef, snapshot: snapshot.value }); emit('saved', saved) } catch (reason) { if (props.follow && isFollowRevisionConflict(reason)) { try { const latest = await loadFollow(props.follow.id); revision.value = latest.revision; applySnapshot(latest.snapshot); error.value = `订阅已在其他页面修改，已加载 revision ${latest.revision}，请确认后重新保存。` } catch { error.value = '订阅已被修改，且最新配置加载失败，请关闭后重试。' } } else error.value = reason instanceof Error ? reason.message : '订阅保存失败' } finally { saving.value = false } }
function closeOnBackdrop(event: MouseEvent) { if (event.target === event.currentTarget) emit('close') }
</script>

<template>
  <div class="dialog-backdrop" @mousedown="closeOnBackdrop">
    <section ref="dialog" class="dialog-panel max-h-[92vh] w-[min(62rem,calc(100vw-2rem))] overflow-y-auto" role="dialog" aria-modal="true" aria-labelledby="follow-editor-title" tabindex="-1" @keydown.esc="emit('close')">
      <header class="semantic-divider sticky top-0 z-1 flex items-start justify-between gap-4 border-b bg-[var(--surface)] p-5"><div><h2 id="follow-editor-title" class="m-0 text-xl">{{ follow ? '编辑订阅策略' : '创建自动追更' }}</h2><p class="page-description mb-0 mt-1 text-sm">{{ title }} · 保存后形成独立策略快照，以后修改系统默认不会改变它。</p></div><button class="btn-secondary" type="button" aria-label="关闭订阅配置" @click="emit('close')">关闭</button></header>
      <div v-if="loading" class="p-10 text-center text-muted">正在读取站点、下载器、媒体库和季信息…</div>
      <div v-else-if="!snapshot || !defaults" class="p-5"><div class="semantic-error p-4">{{ error || '订阅配置不可用' }}</div></div>
      <form v-else class="space-y-5 p-5" @submit.prevent="save">
        <div v-if="error" class="semantic-error p-3" role="alert">{{ error }}</div>
        <section><h3 class="m-0 text-base">1. 选择目标季</h3><p class="page-description mt-1 text-xs">特别篇不会自动包含，必须在这里显式勾选。</p><div class="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><label v-for="season in defaults.coverage.tv?.seasons" :key="season.season_number" class="semantic-list-item flex cursor-pointer items-start gap-3 p-3" :class="seasonUnavailable(season.season_number) ? 'opacity-65' : ''"><img v-if="season.poster_url" class="h-18 w-12 rounded-[var(--radius-sm)] object-cover" :src="season.poster_url" :alt="`${season.name} 季海报`"><input type="checkbox" :checked="snapshot.seasons.includes(season.season_number)" :disabled="seasonUnavailable(season.season_number)" @change="toggleNumber(snapshot.seasons, season.season_number)"><span><span class="flex flex-wrap items-center gap-2"><strong>{{ season.name || `第 ${season.season_number} 季` }}</strong><small v-if="defaults.subscribed_seasons.includes(season.season_number)" class="status-chip status-chip--ready">已订阅</small></span><small class="mt-1 block text-muted">TMDB {{ season.counts.total }} 集 · 已入库 {{ season.counts.present }} · 缺失 {{ season.counts.missing }} · 未播 {{ season.counts.future }} · 未知 {{ season.counts.unknown }}</small></span></label></div></section>
        <section><h3 class="m-0 text-base">2. 下载与入库</h3><p class="page-description mt-1 text-xs">先选择目标媒体库，再选择下载器。115 可处理普通 BT 站点和链接，但不会接收任何 PT 站点资源。</p><div class="mt-3 grid gap-4 lg:grid-cols-2"><div><label class="field-label">目标媒体库</label><select v-model.number="snapshot.media_library_id" class="field-input" @change="syncLibraryRoute"><option :value="0">请选择</option><option v-for="item in defaults.media_libraries" :key="item.id" :value="item.id">{{ item.name }}</option></select></div><div><label class="field-label">下载器</label><select v-model="snapshot.downloader_id" class="field-input" @change="syncDownloaderRoute"><option value="">请选择</option><option v-for="item in routeDownloaders" :key="item.id" :value="item.id">{{ item.name }}</option></select></div></div></section>
        <section><h3 class="m-0 text-base">3. 站点与优先级</h3><p class="page-description mt-1 text-xs">勾选顺序即搜索优先级；选择 115 时这里只显示普通 BT 站点。</p><div class="mt-3 flex flex-wrap gap-2"><label v-for="site in routeSites" :key="site.id" class="semantic-inset flex cursor-pointer items-center gap-2 px-3 py-2"><input type="checkbox" :checked="snapshot.site_ids.includes(site.id)" @change="toggleOrderedNumber(snapshot.site_ids, site.id)">{{ site.name }} · {{ site.site_type.toUpperCase() }}</label></div></section>
        <section class="grid gap-4 sm:grid-cols-3"><div><label class="field-label">检查周期（分钟）</label><input v-model.number="snapshot.schedule.minutes" class="field-input" type="number" min="30" max="10080"></div><div><label class="field-label">单次最多资源</label><input v-model.number="snapshot.max_resources_per_run" class="field-input" type="number" min="1" max="10"></div><div><label class="field-label">下载优先级</label><input v-model.number="snapshot.download_priority" class="field-input" type="number" min="-100" max="100"></div></section>
        <section><h3 class="m-0 text-base">3. 质量与编码</h3><div class="mt-3 grid gap-4 md:grid-cols-3"><fieldset class="semantic-inset p-3"><legend class="px-1 text-sm font-650">分辨率</legend><label v-for="value in resolutionOptions" :key="value" class="mt-2 flex gap-2"><input type="checkbox" :checked="snapshot.filters.resolutions.includes(value)" @change="toggleString(snapshot.filters.resolutions, value)">{{ value }}</label></fieldset><fieldset class="semantic-inset p-3"><legend class="px-1 text-sm font-650">视频编码</legend><label v-for="value in codecOptions" :key="value" class="mt-2 flex gap-2"><input type="checkbox" :checked="snapshot.filters.video_codecs.includes(value)" @change="toggleString(snapshot.filters.video_codecs, value)">{{ value }}</label></fieldset><fieldset class="semantic-inset p-3"><legend class="px-1 text-sm font-650">来源 / 质量</legend><label v-for="value in qualityOptions" :key="value" class="mt-2 flex gap-2"><input type="checkbox" :checked="snapshot.filters.qualities.includes(value)" @change="toggleString(snapshot.filters.qualities, value)">{{ value }}</label></fieldset></div></section>
        <section class="grid gap-4 md:grid-cols-2"><div><label class="field-label">必须包含（逗号分隔）</label><input v-model="includeText" class="field-input" placeholder="例如：简中, WEB"></div><div><label class="field-label">排除关键词</label><input v-model="excludeText" class="field-input" placeholder="例如：CAM, 预告"></div><div><label class="field-label">允许发布组</label><input v-model="releaseText" class="field-input" placeholder="留空表示不限"></div><div><label class="field-label">排除发布组</label><input v-model="excludeReleaseText" class="field-input" placeholder="例如：BADGROUP"></div></section>
        <section class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><label class="field-label">最少做种</label><input v-model.number="snapshot.filters.min_seeders" class="field-input" type="number" min="0"></div><div><label class="field-label">最大年龄（小时）</label><input v-model.number="snapshot.filters.max_age_hours" class="field-input" type="number" min="1" placeholder="不限"></div><div><label class="field-label">最小大小（字节）</label><input v-model.number="snapshot.filters.min_size_bytes" class="field-input" type="number" min="0" placeholder="不限"></div><div><label class="field-label">最大大小（字节）</label><input v-model.number="snapshot.filters.max_size_bytes" class="field-input" type="number" min="1" placeholder="不限"></div></section>
        <div v-if="defaults.unavailable_reason || !defaults.sites.length || !defaults.downloaders.length || !defaults.media_libraries.length" class="semantic-warning p-3">{{ defaults.unavailable_reason || '缺少可用站点、下载器或目标媒体库，请先完成系统配置。' }}</div>
        <footer class="semantic-divider sticky bottom-0 flex flex-wrap items-center justify-between gap-3 border-t bg-[var(--surface)] py-4"><p class="m-0 text-xs text-muted">运行中的任务继续使用启动时 revision；编辑只影响下一次运行。</p><div class="flex gap-2"><button class="btn-secondary" type="button" @click="emit('close')">取消</button><button class="btn-primary" type="submit" :disabled="saving || !ready">{{ saving ? '保存中…' : follow ? '保存新 revision' : '创建并开始追更' }}</button></div></footer>
      </form>
    </section>
  </div>
</template>
